must run without connection

diff --git a/src/scripts/xwconfigure b/src/scripts/xwconfigure
--- a/src/scripts/xwconfigure
+++ b/src/scripts/xwconfigure
@@ -1989,7 +1989,7 @@ echo "Inserting known OpenId servers certificate paths into server keystore"
 echo " - google"
 echo " - yahoo"
 java -cp \$OID_CP \$OID_MAINCLASS --sav
-[ \$? -ne 0 ] &&  fatal "can't run java -cp \$OID_CP \$OID_MAINCLASS --sav"
+[ \$? -ne 0 ] &&  warn "can't run java -cp \$OID_CP \$OID_MAINCLASS --sav"
 
 # previous command generated
 # - open.login.yahooapis.com_0.pem
